FROM centos:8

# Set a gopath where you put your go packages
ENV GOPATH=/go
# lets update debian. you can add a upgrade if you want
RUN yum update -y
RUN yum install git -y
RUN yum install wget -y

WORKDIR /goinstall
RUN wget https://golang.org/dl/go1.15.5.linux-amd64.tar.gz

RUN tar -C /usr/local -xzf go1.15.5.linux-amd64.tar.gz

RUN export PATH=$PATH:/usr/local/go/bin


# get some go packages we will need
RUN go get -v github.com/go-delve/delve/cmd/dlv
RUN go get -v github.com/ramya-rao-a/go-outline
RUN go get -v github.com/rogpeppe/godef
RUN go get -v golang.org/x/tools/gopls





