#goapp

version: '3.4'
services:
  goapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=caleb
    volumes:
      - ./:/go/src/goapp
    ports: 
      - 3000:3000

  user-service:
    image: user-service
    environment: 
      - SECRET="fishsauce"

    volumes:
      - .:/code
    ports:
      - 5000:80
