#goapp

version: '3.4'
services:
  goapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=caleb

    hostname: 'Barbarian'
    environment: 
      - USERSERVICEURL=http://user-service:5000
    
    volumes:
      - ./:/go/src/goapp
    ports: 
      - 3000:3000

  user-service:
    build:
      context: ../pythonjwt
      dockerfile: Dockerfile
      target: developer
    environment: 
      - SECRET="fishsauce"
    command: python3 /app/importer.py
    volumes:
      - ../pythonjwt/:/app
    ports:
      - 5000:5000
