POST http://user-service:80/register HTTP/1.1
content-type: application/json

{
    "username": "caleb2",
    "password": "password",
    "email": "caleb@gmail.com"
 }

###
POST http://user-service:80/login/ HTTP/1.1
content-type: application/json

{
    "username": "caleb2",
    "password": "password"
 }

###


GET http://user-service/user
?token=IntcInN1Y2Nlc3NcIjogZmFsc2UsIFwibWVzc2FnZVwiOiBcInVzZXIgZG9lcyBub3QgZXhpc3RcIiwgXCJ0b2tlblwiOiBcIlwifSI=

###

GET http://localhost:3000/

###

POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "username": "caleb2",
    "password": "password"
}