POST http://jetsonnano.local/register HTTP/1.1
content-type: application/json

{
    "username": "fox",
    "password": "password",
    "email": "caleb@gmail.com"
 }

###
POST http://jetsonnano.local/login/ HTTP/1.1
content-type: application/json

{
    "username": "fox",
    "password": "password"
 }

###


GET http://jetsonnano.local/user
?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImZveCIsImVtYWlsIjoiY2FsZWJAZ21haWwuY29tIiwiaWQiOjQsInRpbWUiOiJcIjIwMjAtMTEtMjYgMTk6NTg6MzMuNjUxMjE4XCIifQ.LUuyOxGw1G6OVy9HCcU63ZVfm8KaeKATx2qA6m4OY7g

###

GET http://localhost:3000/

###

POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "username": "fox",
    "password": "password"
}