POST http://user-service:80/register HTTP/1.1
content-type: application/json

{
    "username": "caleb2",
    "password": "password",
    "email": "caleb@gmail.com"
 }

###
POST http://user-service:80/login/ HTTP/1.1
content-type: application/json

{
    "username": "caleb2",
    "password": "password"
 }

###


GET http://user-service/user
?token=IntcInN1Y2Nlc3NcIjogdHJ1ZSwgXCJtZXNzYWdlXCI6IFwic3VjY2Vzc1wiLCBcInRva2VuXCI6IFwiZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKSVV6STFOaUo5LmV5SjFjMlZ5Ym1GdFpTSTZJbU5oYkdWaUlpd2laVzFoYVd3aU9pSmpZV3hsWWtCbmJXRnBiQzVqYjIwaUxDSnBaQ0k2TVN3aWRHbHRaU0k2SWx3aU1qQXlNQzB4TVMweU5TQXdORG93TVRvek15NHdNRGN3TURWY0lpSjkuZFc0SndkNzNUVHJwWGRtTm5BN2trV3VxaHAwRUlUbTk0aFlzNTNCRkhZOFwifSI=

###

GET http://localhost:3000/

###

POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "username": "caleb",
    "password": "password"
 }